name: ResMelt
main: me.cnaude.resmelt.ResMelt
version: 0.2
author: Chris Naudé 
description: Add "melt" flag to Residence
website: http://dev.bukkit.org/server-mods/resmelt/
harddepend: Residence
permissions:

